export const RESOURCE_ERROR: any = 'globalSagas/RESOURCE_ERROR'
export const RESOURCE_FETCH: any = 'globalSagas/RESOURCE_FETCH'
export const RESOURCES_FETCH: any = 'globalSagas/RESOURCES_FETCH'
export const RESOURCE_CREATE: any = 'globalSagas/RESOURCE_CREATE'
export const RESOURCE_EDIT: any = 'globalSagas/RESOURCE_EDIT'
export const RESOURCE_DELETE: any = 'globalSagas/RESOURCE_DELETE'
export const RESOURCE_SET: any = 'globalSagas/RESOURCE_SET'
