export const RESOURCE_ERROR: string = 'globalSagas/RESOURCE_ERROR'
export const RESOURCE_FETCH: string = 'loop/globalSagas/RESOURCE_FETCH'
export const RESOURCES_FETCH: string = 'loop/globalSagas/RESOURCES_FETCH'
export const RESOURCE_CREATE: string = 'loop/globalSagas/RESOURCE_CREATE'
export const RESOURCE_EDIT: string = 'loop/globalSagas/RESOURCE_EDIT'
export const RESOURCE_DELETE: string = 'loop/globalSagas/RESOURCE_DELETE'
